title: Beyond Survival
description: Beyond Survival: Evaluating LLMs in Social Deduction Games with Human-Aligned Strategies
url: https://ZiruiSongBest.github.io
baseurl: /WereBench


plugins:
  - jekyll-seo-tag

project:
  subtitle: Evaluating LLMs in Social Deduction Games with Human-Aligned Strategies
  paper_url: LINK_TO_ARXIV
  code_url: GITHUB_REPO
  dataset_url: LINK_TO_HF
  authors:
    - { name: "Anonymous"}
  # affiliations:
